server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: Hystrix_Stream
        uri: http://httpbin.org:80
        predicates:
        - Host=**localhost:8088
        - Path=/actuator/hystrix.stream
        filters:
        - Hystrix=Hystrix_Stream
      - id: securityService
        uri: http://localhost:8092/
        predicates:
        - Host=**localhost:8088
        - Path=/**
        filters:
        - Hystrix=SecurityService
        - CustomFilter
      - id: Hystrix_Com
        uri: http://httpbin.org:80
        predicates:
        - Host=*.hystrix.com
        filters:
        - Hystrix=HystrixCom
        
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka  